{% if inventory_hostname_short == "udk_content" or inventory_hostname_short is match(".*_dev") %}
rc_message:
  per_second: 50
  burst_count: 100
{% else %}
#rc_message:
#  per_second: 0.2
#  burst_count: 10
{% endif %}

#rc_registration:
#  per_second: 0.17
#  burst_count: 3

#rc_login:
#  address:
#    per_second: 0.17
#    burst_count: 3
#  account:
#    per_second: 0.17
#    burst_count: 3
#  failed_attempts:
#    per_second: 0.17
#    burst_count: 3

#rc_admin_redaction:
#  per_second: 1
#  burst_count: 50

#rc_joins:
#  local:
#    per_second: 0.1
#    burst_count: 10
#  remote:
#    per_second: 0.01
#    burst_count: 10

#rc_3pid_validation:
#  per_second: 0.003
#  burst_count: 5

{% if inventory_hostname_short == "udk_content" or inventory_hostname_short is match(".*_dev") %}
rc_invites:
  #per_room:
  #  per_second: 0.3
  #  burst_count: 10
  per_user:
    per_second: 50
    burst_count: 100
{% else %}
#rc_invites:
#  per_room:
#    per_second: 0.3
#    burst_count: 10
#  per_user:
#    per_second: 0.003
#    burst_count: 5
{% endif %}

#rc_federation:
#  window_size: 1000
#  sleep_limit: 10
#  sleep_delay: 500
#  reject_limit: 50
#  concurrent: 3
