---
- name: install and configure element-web to /var/www/element_web_root
  hosts: element
  roles:
    - roles/element-web
  vars:
    #element_web_root: classroom
    element_web_root: element
    element_web_version: v1.11.22
